sudo: required
arch: arm64-graviton2
services:
  - docker

script:
 - docker build . -f dockerfile -t wineappimage-arch

env:
  global:
    - RELEASE_BRANCH="master"

after_success:
  # uploadtool
 - wget -c https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh
 - |- # publish
   if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh ./*.AppImage*
   elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh ./*.AppImage*
   else
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh ./*.AppImage*
   fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/
