language: c
sudo: required
dist: focal
os: linux
arch: arm64-graviton2

script:
 - sudo apt-get update
 - sudo apt-get -y install python3 python3-setuptools python3-pip wget patchelf fakeroot gnupg2 libglib2.0-bin file desktop-file-utils libgdk-pixbuf2.0-dev librsvg2-dev zsync
 - sudo mkdir -p /usr/share/icons/hicolor/scalable/ ; sudo cp wine.svg /usr/share/icons/hicolor/scalable/
 - sudo pip3 install appimage-builder
 - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage
 - wget https://gist.githubusercontent.com/mmtrt/8d1a2b9eb33429feb0197ec46b0acdf4/raw/493a1700897897963dba24ffe2985d6e00a71ba1/nvidia_icd.json
 - mv appimagetool-x86_64.AppImage appimagetool && cp appimagetool /home/travis/bin && ls -al && ls -al /home/travis/bin

env:
  global:
    - RELEASE_BRANCH="master"

after_success:
 - appimage-builder --skip-tests --recipe wine-staging-lolp.yml
  # uploadtool
 - wget -c https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh
 - |- # publish
   if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh ./*.AppImage*
   elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh ./*.AppImage*
   else
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh ./*.AppImage*
   fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/
